.TH "Cube.cs" 3 "Thu May 7 2015" "Version 1.0" "ECE590CubeController" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cube.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCubeController\&.Cube\fP"
.br
.ti -1c
.RI "class \fBCubeController\&.Point\fP"
.br
.RI "\fIHelper class\&. Defines a point in x,y,z space\&. Used to eliminate function calling signatures with many x,y,z args needed\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBCubeController\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECE590CubeController from the source code\&.
