.TH "CubeController.Effect" 3 "Thu May 7 2015" "Version 1.0" "ECE590CubeController" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CubeController.Effect \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBTEST_WAVE_ITERATIONS\fP = 1000"
.br
.ti -1c
.RI "const double \fBWAVE_CONSTANT\fP = 9\&.899495"
.br
.RI "\fIA 'magic' number used in some of the original Instructables C-code\&. It seems to be used in connection with finding the distance from the center of the cube when propagating a sinusoidal wave\&. \fP"
.ti -1c
.RI "const double \fBRIPPLE_INTERVAL\fP = 1\&.3"
.br
.ti -1c
.RI "const double \fBHELIX_BRAID_LENGTH_DELTA_T\fP = 0\&.05"
.br
.ti -1c
.RI "const double \fBNICE_SINE_WAVE_DELTA_T\fP = 0\&.75"
.br
.ti -1c
.RI "const int \fBCOMFORTABLE_BOX_WOOP_WOOP_DELAY\fP = 200"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static double \fBPI\fP = 4\&.0 * Math\&.Atan(1\&.0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Effect\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const int CubeController\&.Effect\&.COMFORTABLE_BOX_WOOP_WOOP_DELAY = 200"

.PP
Definition at line 27 of file Effect\&.cs\&.
.SS "const double CubeController\&.Effect\&.HELIX_BRAID_LENGTH_DELTA_T = 0\&.05"

.PP
Definition at line 24 of file Effect\&.cs\&.
.SS "const double CubeController\&.Effect\&.NICE_SINE_WAVE_DELTA_T = 0\&.75"

.PP
Definition at line 25 of file Effect\&.cs\&.
.SS "double CubeController\&.Effect\&.PI = 4\&.0 * Math\&.Atan(1\&.0)\fC [static]\fP"

.PP
Definition at line 23 of file Effect\&.cs\&.
.SS "const double CubeController\&.Effect\&.RIPPLE_INTERVAL = 1\&.3"

.PP
Definition at line 22 of file Effect\&.cs\&.
.SS "const int CubeController\&.Effect\&.TEST_WAVE_ITERATIONS = 1000"

.PP
Definition at line 7 of file Effect\&.cs\&.
.SS "const double CubeController\&.Effect\&.WAVE_CONSTANT = 9\&.899495"

.PP
A 'magic' number used in some of the original Instructables C-code\&. It seems to be used in connection with finding the distance from the center of the cube when propagating a sinusoidal wave\&. The actual definition comes from the original author doing the following: 7 | \\ | \\ A? |___\\ 7 A = sqrt(7^2 + 7^2) ~= 9\&.899495 
.PP
Definition at line 21 of file Effect\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECE590CubeController from the source code\&.
